project:
  type: website
  output-dir: docs



website:
  title: "Dance Jam 2026"

  sidebar:
    background: primary
    logo: "files/128_icon.png"
    pinned: true
    align: center
    style: docked
    contents:
    - section: "About"
      contents:
        - href: index.qmd
          text: Home
        - href: registration.qmd
          text: Registration
        - href: schedule.qmd
          text: Schedule
        - href: contact.qmd
          text: People
    - section: "Event Information"
      contents:
        - href: kickoff.qmd
          text: Jam Weekend
        - href: refinement.qmd
          text: Refinement
        - href: showcase.qmd
          text: Showcase
        - href: discord.qmd
          text: Join the Discord
    - section: "Resources"
      contents:
        - href: dance.qmd
          text: Dance
        - href: algorithms.qmd
          text: Algorithms
        - href: inspiration.qmd
          text: Inspiration

format:
  html:
    theme: simplex
    # css: styles.css
    toc: true

execute:
  freeze: auto

