project:
  type: website
  output-dir: docs

website:
  title: "Introduction to Programming"
  sidebar:
    background: primary
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/chefs-kiss/intro2CS
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: registration.qmd
        text: Registration
      - href: schedule.qmd
        text: Schedule
      - href: kickoff.qmd
        text: Kickoff Weekend
      - href: refinement.qmd
        text: Refinement Weekend
      - href: showcase.qmd
        text: Showcase
      - href: dance.qmd
        text: Dance Background
      - href: Algorithms/background.qmd
        text: Algorithms Background

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto

